//User
export const SET_USER = 'SET_USER'
export const TOGGLE_AUTHENTICATED = 'TOGGLE_AUTHENTICATED'
export const UPDATE_LOGIN_FORM_VALUES = 'UPDATE_LOGIN_FORM_VALUES'
export const UPDATE_SIGNUP_FORM_VALUES = 'UPDATE_SIGNUP_FORM_VALUES'
export const SET_USER_POSTS = 'SET_USER_POSTS'
export const TOGGLE_CREATING_POST = 'TOGGLE_CREATING_POST'
export const TOGGLE_CREATING_TRAIL = 'TOGGLE_CREATING_TRAIL'
export const DELETE_USER = 'DELETE_USER'
export const TOGGLE_DELETE_USER_PASSWORD_INPUT =
  'TOGGLE_DELETE_USER_PASSWORD_INPUT'
export const UPDATE_PASSWORD_BODY = 'UPDATE_PASSWORD_BODY'
export const SET_USER_STATE_TO_DEFAULT = 'SET_USER_STATE_TO_DEFAULT'

//State
export const GET_STATES = 'GET_STATES'
export const GET_STATE_DETAILS = 'GET_STATE_DETAILS'
export const UPDATE_STATE_TRAILS = 'UPDATE_STATE_TRAILS'

//Trail
export const SET_TRAIL = 'SET_TRAIL'
export const CLEAR_TRAIL_FORM = 'CLEAR_TRAIL_FORM'
export const REMOVE_TRAIL = 'REMOVE_TRAIL'
export const UPDATE_NEW_TRAIL_FORM = 'UPDATE_NEW_TRAIL_FORM'
export const EDIT_TRAIL = 'EDIT_TRAIL'
export const POPULATE_TRAIL_FORM = 'POPULATE_TRAIL_FORM'
export const TOGGLE_SHOULD_UPDATE_TRAIL = 'TOGGLE_SHOULD_UPDATE_TRAIL'

//Post
export const SET_POSTS = 'SET_POSTS'
export const CLEAR_POST_FORM = 'CLEAR_POST_FORM'
export const REMOVE_POST = 'REMOVE_POST'
export const UPDATE_NEW_POST_VALUE = 'UPDATE_NEW_POST_VALUE'
export const GET_POSTS_FROM_FOLLOWING_USER = 'GET_POSTS_FROM_FOLLOWING_USER'
// Comment
export const CLEAR_COMMENT_CONTENT = 'CLEAR_COMMENT_CONTENT'
export const UPDATE_COMMENT_CONTENT = 'UPDATE_COMMENT_CONTENT'
export const SET_POST_COMMENTS = 'SET_POST_COMMENTS'
export const TOGGLE_VIEW_COMMENTS = 'TOGGLE_VIEW_COMMENTS'
