//User
export const SET_USER = 'SET_USER'
export const TOGGLE_AUTHENTICATED = 'TOGGLE_AUTHENTICATED'
export const UPDATE_LOGIN_FORM_VALUES = 'UPDATE_LOGIN_FORM_VALUES'
export const UPDATE_SIGNUP_FORM_VALUES = 'UPDATE_SIGNUP_FORM_VALUES'


//State
export const GET_STATES = 'GET_STATES'