//User
export const SET_USER = 'SET_USER'
export const TOGGLE_AUTHENTICATED = 'TOGGLE_AUTHENTICATED'
export const UPDATE_LOGIN_FORM_VALUES = 'UPDATE_LOGIN_FORM_VALUES'
export const UPDATE_SIGNUP_FORM_VALUES = 'UPDATE_SIGNUP_FORM_VALUES'

//State
export const GET_STATES = 'GET_STATES'
export const GET_STATE_DETAILS = 'GET_STATE_DETAILS'

//Trail
export const GET_TRAIL = 'GET_TRAIL'
export const POST_TRAIL = 'NEW_TRAIL'
export const REMOVE_TRAIL = 'REMOVE_TRAIL'
export const UPDATE_NEW_TRAIL_FORM = 'UPDATE_NEW_TRAIL_FORM'
//Post
export const GET_POST = 'GET_POST'
export const POST_POST = 'POST_POST'
export const REMOVE_POST = 'REMOVE_POST'
export const UPDATE_POST = 'UPDATE_POST'
