//User
export const SET_USER = 'SET_USER'
export const TOGGLE_AUTHENTICATED = 'TOGGLE_AUTHENTICATED'
export const UPDATE_LOGIN_FORM_VALUES = 'UPDATE_LOGIN_FORM_VALUES'
export const UPDATE_SIGNUP_FORM_VALUES = 'UPDATE_SIGNUP_FORM_VALUES'
export const SET_USER_POSTS = 'SET_USER_POSTS'
export const TOGGLE_CREATING_POST = 'TOGGLE_CREATING_POST'
export const TOGGLE_CREATING_TRAIL = 'TOGGLE_CREATING_TRAIL'

//State
export const GET_STATES = 'GET_STATES'
export const GET_STATE_DETAILS = 'GET_STATE_DETAILS'

//Trail
export const GET_TRAIL = 'GET_TRAIL'
export const CREATE_TRAIL = 'CREATE_TRAIL'
export const REMOVE_TRAIL = 'REMOVE_TRAIL'
export const UPDATE_NEW_TRAIL_FORM = 'UPDATE_NEW_TRAIL_FORM'
//Post
export const GET_POSTS = 'GET_POSTS'
export const CREATE_POST = 'CREATE_POST'
export const REMOVE_POST = 'REMOVE_POST'
export const UPDATE_NEW_POST_VALUE = 'UPDATE_NEW_POST_VALUE'
export const GET_POSTS_FROM_FOLLOWING_USER = 'GET_POSTS_FROM_FOLLOWING_USER'
// Comment
export const CLEAR_COMMENT_CONTENT = 'CLEAR_COMMENT_CONTENT'
export const UPDATE_COMMENT_CONTENT = 'UPDATE_COMMENT_CONTENT'
export const SET_POST_COMMENTS = 'SET_POST_COMMENTS'
